version: "2.0"
services:
  web:
    container_name: apache_server
    image: arvindr226/alpine-lamp
    ports:
       - "80:80"
       - "443:443"
    volumes:
      - ./html:/var/www/html
#    restart: always
  mysql_db:
    image: mysql:latest
    container_name: mysql_server
#    ports:
#      - 3306:3306
    environment:
      MYSQL_DATABASE: gotechnies
      MYSQL_USER: gotechnies
      MYSQL_PASSWORD: gotechnies
      MYSQL_ROOT_PASSWORD: gotechnies
#    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
#    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions

#Note-: If you want to restart the docker container on system start up, uncomment the restart:always line.
